version: '3'
services:
  app:
    container_name: currency-converter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis-stack-server
    networks:
      - backend-network

  redis-stack-server:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - backend-network

volumes:
  redis-data:

networks:
  backend-network:
    driver: bridge
